---
apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-demo-deploy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: newa/api-demo:1.0
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            value: ":443"
        volumeMounts:
          - name: demo-api-tls
            mountPath: "/tmp"
            readOnly: true
      volumes:
        - name: api-demo-tls
          secret:
            secretName: api-demo-tls

---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-svc
  namespace: dempo
  labels:
    app: api-demo
spec:
  type: ClusterIP
  ports:
  - port: 443
    name: https
  selector:
    app: api-demo