---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-demo-deploy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: newa/demo-api:1.0
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            value: ":443"
        volumeMounts:
          - name: api-demo-tls
            mountPath: "/tmp"
            readOnly: true
      volumes:
        - name: api-demo-tls
          secret:
            secretName: api-demo-tls

---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-svc
  namespace: demo
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: demo-demo-api-transport@kubernetescrd
  labels:
    app: api-demo
spec:
  type: ClusterIP
  ports:
  - port: 443
    name: https
  selector:
    app: api-demo

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: demo-api-transport
  namespace: demo
spec:
  serverName: gateway.domain.tld
  insecureSkipVerify: true

---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: demo-api
  namespace: demo
  labels:
    area: demo
spec:
  pathPrefix: /newline
  service:
    name: api-demo-svc
    openApiSpec:
      path: /toto.yaml
      port:
        number: 443
    port:
      number: 443

#---
#apiVersion: traefik.io/v1alpha1
#kind: IngressRoute
#metadata:
#  name: demo-tls
#  namespace: demo
#spec:
#  entryPoints:
#    - websecure
#  routes:
#    - kind: Rule
#      match: Host(`demo-api.domain.tld`)
#      services:
#        - name: api-demo-svc
#          port: 443
#          serversTransport: demo-api-transport
#  tls: {}